name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../../

    steps:
    - uses: actions/checkout@v3
    - name: C++ linters and formatters
      # You may pin to the exact commit or the version.
      # uses: ArtificialAmateur/cpp-linter-action@6281cc1ef3abe25ee492f19f7d8b184ca873db34
      uses: cpp-linter/cpp-linter-action@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        style: .clang-format
        repo-root: ../..
    - name: make
      run: |
        make
        


